Gis.PL/Controllers/MarketController.cs
using AutoMapper;
using Gis.BLL.UnitOfWork;
using Gis.DAL.Models;
using Gis.PL.Dtos;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Gis.PL.Controllers
{
    [Authorize]
    public class MarketController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;

        public MarketController(IUnitOfWork unitOfWork, IMapper mapper)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
        }

        [HttpGet]
        public async Task<ActionResult> Index(string SearchInput)
        {

            IEnumerable<Market> Markets;
            if (string.IsNullOrEmpty(SearchInput))
            {
                Markets = await _unitOfWork.MarketRepository.GetAllAsync();
            }
            else
            {
                Markets = await _unitOfWork.MarketRepository.GetByNameAsync(SearchInput);
            }
            return View(Markets);

        }
        [HttpGet]
        public async Task<ActionResult> Search(string SearchInput)
        {
            IEnumerable<Market> Markets;
            if (string.IsNullOrEmpty(SearchInput))
            {
                Markets = await _unitOfWork.MarketRepository.GetAllAsync();
            }
            else
            {
                Markets = await _unitOfWork.MarketRepository.GetByNameAsync(SearchInput);
            }
            return PartialView("MarketPartialView/MarketTablePartialView", Markets);
        }
        [HttpGet]
        [Authorize(Roles = "SuperAdmin,Admin")]


        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(MarketDto model)
        {
            if (ModelState.IsValid)
            {
                var Markets = _mapper.Map<Market>(model);
                await _unitOfWork.MarketRepository.AddAsync(Markets);
                var count = await _unitOfWork.CompleteAsync();
                if (count > 0)
                {
                    TempData["Message"] = "Market Is Created !!";
                    return RedirectToAction("Index");
                }
            }
            return View(model);
        }
        [HttpGet]

        public async Task<IActionResult> Details(int? id, string ViewName = "Details")
        {
            if (id is null) return BadRequest("Invaliad Id");
            var Market = await _unitOfWork.MarketRepository.GetAsync(id.Value);
            if (Market is null) return NotFound(new { StatusCode = 404, Message = $"Market With Id {id} is not Found " });
            var MarketDto = _mapper.Map<MarketDto>(Market);
            return View(ViewName, MarketDto);
        }
        [HttpGet]
        [Authorize(Roles = "SuperAdmin,Admin")]


        public async Task<IActionResult> Edit(int? id)
        {

            return await Details(id, "Edit");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] int id, MarketDto model)
        {
            if (ModelState.IsValid)
            {

                var Market = _mapper.Map<Market>(model);
                Market.Objectid = id;
                _unitOfWork.MarketRepository.Update(Market);
                var count = await _unitOfWork.CompleteAsync();
                if (count > 0)
                {
                    return RedirectToAction("Index");
                }
            }
            return View(model);
        }
        [Authorize(Roles = "SuperAdmin,Admin")]

        public async Task<IActionResult> Delete(int? id)
        {

            return await Details(id, "Delete");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete([FromRoute] int id, MarketDto model)
        {
            if (ModelState.IsValid)
            {
                var Market = _mapper.Map<Market>(model);
                Market.Objectid = id;
                _unitOfWork.MarketRepository.Delete(Market);
                var count = await _unitOfWork.CompleteAsync();
                if (count > 0)
                {
                    return RedirectToAction("Index");
                }

            }
            return View(model);
        }
    }
}

Gis.PL/Controllers/RoleController.cs
using Gis.DAL.Models;
using Gis.PL.Dtos;
using Gis.PL.Dtos.Auth;
using Gis.PL.Healper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Company.G04.PL.Controllers
{
    [Authorize(Roles = "SuperAdmin")]
    
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<AppUser> _userManager;

        public RoleController(RoleManager<IdentityRole> roleManager, UserManager<AppUser> userManager)
        {
            _roleManager = roleManager;
           _userManager = userManager;
        }
        [HttpGet]
        public async Task<ActionResult> Index(string SearchInput)
        {

            IEnumerable<RoleToReturnDto> roles;
            if (string.IsNullOrEmpty(SearchInput))
            {
                roles = _roleManager.Roles.Select(U => new RoleToReturnDto()
                {
                    Id = U.Id,
                    Name = U.Name,

                });
            }
            else
            {
                roles = _roleManager.Roles.Select(U => new RoleToReturnDto()
                {
                    Id = U.Id,
                    Name = U.Name,

                }).Where(U => U.Name.ToLower().Contains(SearchInput.ToLower()));
            }
            return View(roles);
        }
        [HttpGet]
        public ActionResult Create()
        {

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(RoleToReturnDto model)
        {
            if (ModelState.IsValid)
            {
                var role = await _roleManager.FindByNameAsync(model.Name);
                if (role is null)
                {
                    role = new IdentityRole()
                    {
                        Name = model.Name,
                    };
                    var result = await _roleManager.CreateAsync(role);
                    if (result.Succeeded)
                    {
                        TempData[key: "Message"] = "Role Is Created !!";

                        return RedirectToAction("Index");
                    }
                }
            }
            return View(model);

        }
        [HttpGet]
        public async Task<ActionResult> Details(string? id, string ViewName = "Details")
        {
            if (id is null) return BadRequest();
            var role = await _roleManager.FindByIdAsync(id);
            if (role is null) return NotFound(new { StatusCode = 404, Message = $"Department With Id {id} is not Found " });
            var roleDto = new RoleToReturnDto()
            {
                Id = role.Id,
                Name = role.Name,

            };

            return View(ViewName, roleDto);
        }

        [HttpGet]
        public async Task<ActionResult> Edit(string? id)
        {

            return await Details(id, "Edit");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([FromRoute] string id, RoleToReturnDto model)
        {
            if (ModelState.IsValid)
            {

                if (id != model.Id) return BadRequest("Invailed Operation !");
                var role = await _roleManager.FindByIdAsync(id);
                if (role is null) return BadRequest("Invailed Operation !");
                var roleResult = await _roleManager.FindByNameAsync(model.Name);
                if (roleResult is null)
                {
                    role.Name = model.Name;
                    var result = await _roleManager.UpdateAsync(role);
                    {
                        if (result.Succeeded)
                        {

                            return RedirectToAction("Index");
                        }
                    }
                }
                ModelState.AddModelError("", "Invalid Operation ");



            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string? id)
        {

            return await Details(id, "Delete");


        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete([FromRoute] string id, RoleToReturnDto model)
        {

            if (ModelState.IsValid)
            {

                if (id != model.Id) return BadRequest("Invailed Operation !");
                var role = await _roleManager.FindByIdAsync(id);
                if (role is null) return BadRequest("Invailed Operation !");

                var result = await _roleManager.DeleteAsync(role);
                {
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                }

                ModelState.AddModelError("", "Invalid Operation ");
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> AddOrRemoveUser(string roleId)
        {
           var role = await _roleManager.FindByIdAsync(roleId);
            if (role is null) return NotFound();
            ViewData["RoleId"] = roleId;
            var usersInRole = new List<UserInRoleDto>();
            var users = await _userManager.Users.ToListAsync();
            foreach (var user in users)
            {
                var userInRole = new UserInRoleDto()
                {
                    UserId = user.Id,
                    UserName = user.UserName,

                };
                if(await _userManager.IsInRoleAsync(user, role.Name))
                {
                    userInRole.IsSelected = true;
                }
                else
                {
                    userInRole.IsSelected = false;
                }
                usersInRole.Add(userInRole);


            }
            return View(usersInRole);
            


        }
        [HttpPost]
        public async Task<IActionResult> AddOrRemoveUser( string  roleId,List<UserInRoleDto> users)
        {
            var role = await _roleManager.FindByIdAsync(roleId);
            if (role is null) return NotFound();
            if (ModelState.IsValid)
            {
                foreach (var user in users)
                {
                    var appUser =await _userManager.FindByIdAsync(user.UserId);
                    if (appUser is not null)
                    {
                        if (user.IsSelected && ! await _userManager.IsInRoleAsync(appUser,role.Name))
                        {
                            await _userManager.AddToRoleAsync(appUser, role.Name);
                        }
                        else if (!user.IsSelected && await _userManager.IsInRoleAsync(appUser, role.Name))
                        {
                            await _userManager.RemoveFromRoleAsync(appUser, role.Name);

                        }
                    }
                }
                return RedirectToAction(nameof(Edit), new {id = roleId});
            }

            return View(users);
        }


    }
}

Gis.PL/Controllers/UserController.cs
using Gis.DAL.Models;
using Gis.PL.Dtos;
using Gis.PL.Dtos.Auth;
using Gis.PL.Healper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Gis.PL.Controllers
{
    [Authorize(Roles = "SuperAdmin,Admin")]

    public class UserController : Controller
    {
        private readonly UserManager<AppUser> _userManager;

        public UserController(UserManager<AppUser> userManager)
        {
          _userManager = userManager;
        }
        [HttpGet]
        public async Task<ActionResult> Index(string SearchInput)
        {
            
            IEnumerable<UserToReturnDto> users;
            if (string.IsNullOrEmpty(SearchInput))
            {
              users = _userManager.Users.Select(U => new UserToReturnDto()
                {
                    Id = U.Id,
                    UserName = U.UserName,
                    FirstName = U.FirstName,
                    LastName = U.LastName,
                    Email = U.Email,
                    Roles = _userManager.GetRolesAsync(U).Result
                });
            }
            else
            {
             users = _userManager.Users.Select(U => new UserToReturnDto()
                {
                    Id = U.Id,
                    UserName = U.UserName,
                    FirstName = U.FirstName,
                    LastName = U.LastName,
                    Email = U.Email,
                 Roles = _userManager.GetRolesAsync(U).Result
                }).Where(U => U.FirstName.ToLower().Contains(SearchInput.ToLower()));
            } 
            return View(users);
        }
        public async Task<ActionResult> Search(string SearchInput)
        {

            IEnumerable<UserToReturnDto> users;
            if (string.IsNullOrEmpty(SearchInput))
            {
                users = _userManager.Users.Select(U => new UserToReturnDto()
                {
                    Id = U.Id,
                    UserName = U.UserName,
                    FirstName = U.FirstName,
                    LastName = U.LastName,
                    Email = U.Email,
                    Roles = _userManager.GetRolesAsync(U).Result
                });
            }
            else
            {
                users = _userManager.Users.Select(U => new UserToReturnDto()
                {
                    Id = U.Id,
                    UserName = U.UserName,
                    FirstName = U.FirstName,
                    LastName = U.LastName,
                    Email = U.Email,
                    Roles = _userManager.GetRolesAsync(U).Result
                }).Where(U => U.FirstName.ToLower().Contains(SearchInput.ToLower()));
            }
            return PartialView("UserPartailView/UserTablePartialView", users);
        }
        [HttpGet]
        public async Task<ActionResult> Details(string? id, string ViewName = "Details")
        {
            if (id is null) return BadRequest();
            var user  = await _userManager.FindByIdAsync(id);
            if (user is null) return NotFound(new { StatusCode = 404, Message = $"Department With Id {id} is not Found " });
            var userDto = new UserToReturnDto()
            {
                Id = user.Id,
                UserName = user.UserName,
                FirstName = user.FirstName,
                LastName = user.LastName,
                Email = user.Email,
                Roles = _userManager.GetRolesAsync(user).Result
            };

            return View(ViewName, userDto);
        }

        [HttpGet]
        public async Task<ActionResult> Edit(string? id)
        {
           
            return await Details(id ,"Edit");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([FromRoute] string id, UserToReturnDto model)
        {
            if (ModelState.IsValid)
            {

                if (id != model.Id) return BadRequest("Invailed Operation !");
                var user = await _userManager.FindByIdAsync(id);
                if (user is null) return BadRequest("Invailed Operation !");
                user.UserName = model.UserName;
                user.FirstName = model.FirstName;
                user.LastName = model.LastName;
                user.Email = model.Email;

                var result = await _userManager.UpdateAsync(user);
                {
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                }
            }

                return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string ? id)
        {

            return await Details(id, "Delete");


        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete([FromRoute] string id, UserToReturnDto model)
        {

            if (ModelState.IsValid)
            {

                if (id != model.Id) return BadRequest("Invailed Operation !");
                var user = await _userManager.FindByIdAsync(id);
                if (user is null) return BadRequest("Invailed Operation !");
               

                var result = await _userManager.DeleteAsync(user);
                {
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                }
            }

            return View(model);
        }
    }
    }

Gis.PL/Views/Shared/ButtonPartialView.cshtml
@model string
<td>
    <a asp-action="Details" asp-route-id="@Model" class="btn btn-warning">
        <i class="fas fa-eye"></i> Details
    </a>
</td>
<td>
    <a asp-action="Edit" asp-route-id="@Model" class="btn btn-success">
        <i class="fas fa-edit"></i> Update
    </a>
</td>
<td>
    <a asp-action="Delete" asp-route-id="@Model" class="btn btn-danger">
        <i class="fas fa-trash"></i> Delete
    </a>
    @*  <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal">
        <i class="fas fa-trash"></i> Delete
    </button> *@
</td>

Gis.PL/Views/Shared/_AuthLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>

    <!-- Custom Styles -->
    <link rel="shortcut icon" type="image/png" href="~/files/logo/G02.png" />

    <link href="~/css/gps.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/AuthStyleSheet.css" />

    <!-- Boxicons -->
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet' />

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@100..900&display=swap" rel="stylesheet" />
</head>

<body>
    <!-- Animated GPS Background -->
    <header class="hero hero--map gps-bg">
        <div class="gps-bg__guts">
            <div class="gps-bg__bg"></div>
            <div class="gps-bg__route"></div>
            <div class="gps-bg__marker"></div>
        </div>
        <div class="gps-bg__fade"></div>

        <h1 class="hero__title">Welcome to G02 Housing GIS</h1>
    </header>

    <!-- Foreground Content -->
    <div class="content-wrapper">
        @RenderBody()
    </div>

    <!-- Scripts -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/Script.js"></script>
    @await RenderSectionAsync("ValidationSection", required: false)
</body>
</html>

Gis.PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8" />
    <title>@ViewData["Title"] -  Housing GIS</title>
<link rel="shortcut icon" type="image/png" href="~/files/logo/G02.png" />
    <link href="~/css/styles.css" rel="stylesheet" />
    <link href="~/lib/leaflet/leaflet.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" />
</head>

<body>

    <style>
        .footer {
            background-color: #343a40; 
            color: #ffffff;
            font-size: 14px;
            border-top: 2px solid #198754; 
        }

            .footer span {
                display: inline-block;
                padding: 5px 10px;
            }

    </style>
    <header>
        <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
            <!-- Navbar Brand-->
            <a class="navbar-brand ps-3 d-flex align-items-center" asp-controller="Home" asp-action="Index">
                <img src="~/files/logo/g02.png" alt="Logo" style="height: 32px; margin-right: 10px;" />
                <span class="fw-bold"> Housing </span>
            </a>


            <!-- Sidebar Toggle-->
            <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
            <!-- Navbar Right Menu-->
            <div class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
                <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="fas fa-user fa-fw"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="#!">Settings</a></li>
                            <li><a class="dropdown-item" href="#!">Activity Log</a></li>
                            <li><hr class="dropdown-divider" /></li>
                            <li><a class="dropdown-item" asp-controller="Account" asp-action="SignOut">Logout</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
    </header>

    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Security</div>
                        <a class="nav-link" asp-controller="Role" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-user"></i></div>
                            Roles
                        </a>
                        <a class="nav-link" asp-controller="User" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-users"></i></div>
                            Users
                        </a>

                        <div class="sb-sidenav-menu-heading">Website</div>
                        <a class="nav-link" asp-controller="Mosques" asp-action="Index">
                            <div class="sb-nav-link-icon"></div>
                            🕌 Mosques
                        </a>
                        <a class="nav-link" asp-controller="Restaurant" asp-action="Index">
                            <div class="sb-nav-link-icon"></div>
                            🍽️ Restaurants

                        </a>
                        <a class="nav-link" asp-controller="Pharmacy" asp-action="Index">
                            <div class="sb-nav-link-icon"></div>
                            💊 Pharmacies
                        </a>
                        <a class="nav-link" asp-controller="Market" asp-action="Index">
                            <div class="sb-nav-link-icon"></div>
                            🛒 SuperMarkets

                        </a>
                        <a class="nav-link" asp-controller="StudentHousing" asp-action="Index">
                            <div class="sb-nav-link-icon"></div>
                            🎓🏠 Student Housings

                        </a>
                    </div>
                </div>
            </nav>
        </div>

        <div id="layoutSidenav_content">
            <div class="container">
                <main role="main" class="pb-3">
                    <script src="~/lib/jquery/dist/jquery.min.js"></script>

                    <script src="~/jquery-ajaxy/scripts/jquery.ajaxy.min.js"></script>
                    @RenderBody()
                </main>
            </div>
        </div>
    </div>

    <footer class="footer bg-dark text-white py-3 mt-auto">
        <div class="container text-start">
            <span>&copy; 2025 - Gis.OmarAlshandidy | All rights reserved</span>
        </div>
    </footer>

    <!-- Scripts -->
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    <script src="~/jquery-ajaxy/scripts/jquery.ajaxy.min.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/scripts.js"></script>
    <script src="~/js/datatables-simple-demo.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @await RenderSectionAsync("ValidionSection", required: false)

</body>
</html>